name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-graalvm@3
      with:
        graalvm-version: '20.1.0.java11'
    - run: java -version
    - run: gu install native-image
    - run: |
        cd quarker
        ./mvnw package -x test -Dquarkus.package.type=native
        
  docker_build_push:
      runs-on: ubuntu-latest
      steps:
        - uses: docker/build-push-action@v1.1.0
          with:
            username: tmplcl
            password: ${{ secrets.DOCKERHUB }}
            repository: tmplcl/microstuff
            dockerfile: quarker/src/main/docker/Dockerfile.native
            path: quarker
          
          
      
      
